FROM debian:jessie
#This dockfile add some basic system and networking programs.
MAINTAINER Magnus Kronnäs

################################################################
#       Basic apps                                             #
################################################################

RUN apt-get update && apt-get install -y \
		nano \
		git \
		htop \
		wget
