FROM krmit/ssh
#This dockfile add networking tools.
MAINTAINER Magnus Kronnäs

################################################################
#       Networking tools                                       #
################################################################

RUN apt-get update && apt-get install -y \
		curl \
		nmap \
		openssh-client \
		traceroute
