FROM krmit/core
#This dock file add system and networking programs.
MAINTAINER Magnus Kronnäs

# Networking tools
RUN apt-get update && apt-get install -y \
		curl \
		nmap \
		openssh-client \
		traceroute \
		tshark
